import numpy as np
from elastica import CosseratRod
from numpy.typing import NDArray

from .tapered_geometry import allocate


def create_arm(
    n_elements: int,
    start: NDArray[np.float64],
    direction: NDArray[np.float64],
    normal: NDArray[np.float64],
    base_length: float,
    base_radius: float,
    density: float,
    youngs_modulus: float,
):
    ring_rod_flag = False
    (
        n_elements,
        position,
        velocities,
        omegas,
        accelerations,
        angular_accelerations,
        directors,
        radius,
        mass_second_moment_of_inertia,
        inv_mass_second_moment_of_inertia,
        shear_matrix,
        bend_matrix,
        density_array,
        volume,
        mass,
        internal_forces,
        internal_torques,
        external_forces,
        external_torques,
        lengths,
        rest_lengths,
        tangents,
        dilatation,
        dilatation_rate,
        voronoi_dilatation,
        rest_voronoi_lengths,
        sigma,
        kappa,
        rest_sigma,
        rest_kappa,
        internal_stress,
        internal_couple,
    ) = allocate(
        n_elements,
        start,
        direction,
        normal,
        np.float64(base_radius),
        np.float64(density),
        np.float64(youngs_modulus),
    )

    return CosseratRod(
        n_elements,
        position,
        velocities,
        omegas,
        accelerations,
        angular_accelerations,
        directors,
        radius,
        mass_second_moment_of_inertia,
        inv_mass_second_moment_of_inertia,
        shear_matrix,
        bend_matrix,
        density_array,
        volume,
        mass,
        internal_forces,
        internal_torques,
        external_forces,
        external_torques,
        lengths,
        rest_lengths,
        tangents,
        dilatation,
        dilatation_rate,
        voronoi_dilatation,
        rest_voronoi_lengths,
        sigma,
        kappa,
        rest_sigma,
        rest_kappa,
        internal_stress,
        internal_couple,
        ring_rod_flag,
    )

